-- ============================================================
-- MILHANO | V15 | EOD EDITING + CHANGE LOGS
-- Date: 2026-08-18
--
-- Goals
-- 1) EOD values are FINAL TOTALS, never deltas.
--    Example: correcting 20 -> 22 means save 22, not +2.
-- 2) Advisors may correct their own already-submitted EOD.
--    Validated EODs remain admin-only.
-- 3) Every save/update stores a compact field-level audit record.
-- 4) Existing EOD action history remains intact.
--
-- The CSV GHL-gap report is generated by the dashboard from the
-- existing reconciliation RPC; it requires no extra database table.
-- ============================================================

begin;

-- ------------------------------------------------------------
-- A. Dedicated simple EOD change log.
-- ------------------------------------------------------------
create table if not exists public.milhano_eod_change_logs (
    id uuid primary key default gen_random_uuid(),
    submission_id uuid not null references public.milhano_eod_submissions(id) on delete cascade,
    actor_app_user_id uuid references public.milhano_app_users(id),
    target_app_user_id uuid not null references public.milhano_app_users(id),
    eod_date date not null,
    action_type text not null,
    status_before text,
    status_after text,
    changes jsonb not null default '[]'::jsonb,
    changed_fields integer not null default 0,
    comments_before text,
    comments_after text,
    created_at timestamptz not null default now(),
    constraint milhano_eod_change_logs_action_type_check
      check (action_type in ('save_draft', 'submit', 'edit_submitted', 'admin_edit')),
    constraint milhano_eod_change_logs_changes_array_check
      check (jsonb_typeof(changes) = 'array')
);

create index if not exists idx_milhano_eod_change_logs_created_at
    on public.milhano_eod_change_logs (created_at desc);

create index if not exists idx_milhano_eod_change_logs_eod_date
    on public.milhano_eod_change_logs (eod_date desc);

create index if not exists idx_milhano_eod_change_logs_actor
    on public.milhano_eod_change_logs (actor_app_user_id, created_at desc);

-- Keep the legacy action table vocabulary compatible with the new edit events.
alter table public.milhano_eod_submission_actions
    drop constraint if exists milhano_eod_submission_actions_action_type_check;

alter table public.milhano_eod_submission_actions
    add constraint milhano_eod_submission_actions_action_type_check
    check (
        action_type in (
            'save_draft',
            'submit',
            'blocked',
            'validate',
            'open_historical',
            'edit_submitted',
            'admin_edit'
        )
    );

-- Simple read view used by /logs.
create or replace view public.vw_milhano_eod_change_logs
with (security_invoker = true)
as
select
    l.id,
    l.submission_id,
    l.created_at,
    l.eod_date,
    l.action_type,
    l.status_before,
    l.status_after,
    l.changed_fields,
    l.changes,
    l.comments_before,
    l.comments_after,
    l.actor_app_user_id,
    actor.display_name as actor_name,
    l.target_app_user_id,
    target.display_name as advisor_name
from public.milhano_eod_change_logs l
left join public.milhano_app_users actor
  on actor.id = l.actor_app_user_id
join public.milhano_app_users target
  on target.id = l.target_app_user_id;

-- ------------------------------------------------------------
-- B. Rebuild EOD save function.
-- ------------------------------------------------------------
create or replace function public.milhano_save_eod_submission(
    p_submission_id uuid,
    p_actor_app_user_id uuid,
    p_metrics jsonb,
    p_comments text default null,
    p_submit boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_submission public.milhano_eod_submissions%rowtype;
    v_actor public.milhano_app_users%rowtype;
    v_target public.milhano_app_users%rowtype;
    v_metric jsonb;
    v_metric_key text;
    v_declared integer;
    v_old_declared integer;
    v_manual_extra integer;
    v_note text;
    v_old_status text;
    v_new_status text;
    v_action_type text;
    v_reported_gaps integer := 0;
    v_missing integer := 0;
    v_changes jsonb := '[]'::jsonb;
    v_changed_fields integer := 0;
    v_old_comments text;
    v_new_comments text;
    v_comments_changed boolean := false;
    v_is_closed_edit boolean := false;
begin
    select * into v_actor
    from public.milhano_app_users
    where id = p_actor_app_user_id
      and is_active = true;

    if not found then
        raise exception 'Actor no válido o inactivo';
    end if;

    select * into v_submission
    from public.milhano_eod_submissions
    where id = p_submission_id
    for update;

    if not found then
        raise exception 'Submission EOD no encontrada';
    end if;

    select * into v_target
    from public.milhano_app_users
    where id = v_submission.app_user_id;

    if not found then
        raise exception 'Asesora del EOD no encontrada';
    end if;

    if v_actor.role = 'viewer' then
        raise exception 'La cuenta de dirección es de sólo lectura';
    end if;

    if v_actor.role <> 'admin' and v_actor.id <> v_submission.app_user_id then
        raise exception 'No tienes permiso para editar este cierre';
    end if;

    -- Advisors may correct their own submitted EOD, but a validated EOD is
    -- considered formally closed and remains admin-only.
    if v_submission.status = 'validated' and v_actor.role <> 'admin' then
        raise exception 'El EOD ya fue validado. Solicita a un administrador la corrección';
    end if;

    if p_metrics is null or jsonb_typeof(p_metrics) <> 'array' then
        raise exception 'p_metrics debe ser un arreglo JSON';
    end if;

    v_old_status := v_submission.status;
    v_old_comments := v_submission.comments;
    v_new_comments := nullif(trim(p_comments), '');
    v_comments_changed := v_old_comments is distinct from v_new_comments;
    v_is_closed_edit := v_old_status in ('submitted', 'validated');

    for v_metric in
        select value from jsonb_array_elements(p_metrics)
    loop
        v_metric_key := nullif(trim(v_metric ->> 'metric_key'), '');
        if v_metric_key is null then
            continue;
        end if;

        if not exists (
            select 1
            from public.milhano_eod_metric_catalog c
            where c.metric_key = v_metric_key
              and c.is_active = true
              and c.is_system_only = false
        ) then
            continue;
        end if;

        begin
            v_declared := nullif(trim(v_metric ->> 'declared_value'), '')::integer;
        exception when others then
            raise exception 'Valor reportado inválido para %', v_metric_key;
        end;

        if v_declared is not null and v_declared < 0 then
            raise exception 'El valor reportado no puede ser negativo para %', v_metric_key;
        end if;

        select mv.declared_value, coalesce(mv.manual_extra_value, 0)
        into v_old_declared, v_manual_extra
        from public.milhano_eod_metric_values mv
        where mv.submission_id = p_submission_id
          and mv.metric_key = v_metric_key;

        if not found then
            v_old_declared := null;
            v_manual_extra := 0;
        end if;

        if v_metric ? 'manual_extra_value' then
            begin
                v_manual_extra := coalesce(
                    nullif(trim(v_metric ->> 'manual_extra_value'), '')::integer,
                    0
                );
            exception when others then
                raise exception 'Manual Extra inválido para %', v_metric_key;
            end;
        end if;

        v_note := nullif(trim(v_metric ->> 'discrepancy_note'), '');

        -- IMPORTANT: declared_value is an absolute final total. This update
        -- REPLACES the previous value; it never adds a delta.
        insert into public.milhano_eod_metric_values (
            submission_id,
            metric_key,
            system_value,
            declared_value,
            manual_extra_value,
            user_confirmed,
            discrepancy_note,
            updated_at
        )
        select
            p_submission_id,
            v_metric_key,
            coalesce(existing.system_value, 0),
            v_declared,
            v_manual_extra,
            (v_declared is not null),
            coalesce(v_note, existing.discrepancy_note),
            now()
        from (
            select system_value, discrepancy_note
            from public.milhano_eod_metric_values
            where submission_id = p_submission_id
              and metric_key = v_metric_key
        ) existing
        right join (select 1) seed on true
        on conflict (submission_id, metric_key)
        do update set
            declared_value = excluded.declared_value,
            manual_extra_value = excluded.manual_extra_value,
            user_confirmed = excluded.user_confirmed,
            discrepancy_note = excluded.discrepancy_note,
            updated_at = now();

        if v_old_declared is distinct from v_declared then
            v_changes := v_changes || jsonb_build_array(
                jsonb_build_object(
                    'metric_key', v_metric_key,
                    'old_value', v_old_declared,
                    'new_value', v_declared
                )
            );
            v_changed_fields := v_changed_fields + 1;
        end if;
    end loop;

    select
        count(*) filter (
            where not c.is_system_only
              and mv.declared_value is null
        ),
        count(*) filter (
            where not c.is_system_only
              and mv.declared_value is not null
              and mv.declared_value <>
                  coalesce(mv.system_value, 0) + coalesce(mv.manual_extra_value, 0)
        )
    into v_missing, v_reported_gaps
    from public.milhano_eod_metric_catalog c
    left join public.milhano_eod_metric_values mv
      on mv.submission_id = p_submission_id
     and mv.metric_key = c.metric_key
    where c.is_active = true;

    -- Existing submitted/validated EODs remain submitted after a correction.
    -- A validated EOD edited by an admin loses validation because the data changed.
    if v_is_closed_edit then
        v_new_status := 'submitted';
        v_action_type := case
            when v_actor.role = 'admin' then 'admin_edit'
            else 'edit_submitted'
        end;
    elsif p_submit then
        v_new_status := 'submitted';
        v_action_type := 'submit';
    else
        v_new_status := 'draft';
        v_action_type := 'save_draft';
    end if;

    update public.milhano_eod_submissions
    set
        status = v_new_status,
        comments = v_new_comments,
        submitted_at = case
            when v_new_status = 'submitted' then coalesce(submitted_at, now())
            else submitted_at
        end,
        validated_at = case
            when v_old_status = 'validated'
                 and (v_changed_fields > 0 or v_comments_changed)
                then null
            else validated_at
        end,
        validated_by_app_user_id = case
            when v_old_status = 'validated'
                 and (v_changed_fields > 0 or v_comments_changed)
                then null
            else validated_by_app_user_id
        end,
        updated_at = now()
    where id = p_submission_id;

    -- Existing technical action history.
    insert into public.milhano_eod_submission_actions (
        submission_id,
        actor_app_user_id,
        action_type,
        old_status,
        new_status,
        comments,
        details
    )
    values (
        p_submission_id,
        p_actor_app_user_id,
        v_action_type,
        v_old_status,
        v_new_status,
        v_new_comments,
        jsonb_build_object(
            'submit_requested', p_submit,
            'missing_reported_values', v_missing,
            'reported_gaps', v_reported_gaps,
            'blocking_mismatches', 0,
            'changed_fields', v_changed_fields,
            'changes', v_changes,
            'comments_changed', v_comments_changed,
            'value_semantics', 'absolute_total_replace_not_delta',
            'policy', 'v15_editable_logged_eod'
        )
    );

    -- Human-readable log source used by /logs.
    insert into public.milhano_eod_change_logs (
        submission_id,
        actor_app_user_id,
        target_app_user_id,
        eod_date,
        action_type,
        status_before,
        status_after,
        changes,
        changed_fields,
        comments_before,
        comments_after
    )
    values (
        p_submission_id,
        p_actor_app_user_id,
        v_submission.app_user_id,
        v_submission.eod_date,
        v_action_type,
        v_old_status,
        v_new_status,
        v_changes,
        v_changed_fields,
        v_old_comments,
        v_new_comments
    );

    return jsonb_build_object(
        'ok', true,
        'result', case
            when v_is_closed_edit then 'updated'
            when p_submit then 'submitted'
            else 'saved'
        end,
        'submission_id', p_submission_id,
        'status', v_new_status,
        'changed_fields', v_changed_fields,
        'missing_or_unconfirmed', v_missing,
        'reported_gaps', v_reported_gaps,
        'blocking_mismatches', 0,
        'value_semantics', 'absolute_total_replace_not_delta',
        'processed_at', now()
    );
end;
$$;

revoke all on function public.milhano_save_eod_submission(uuid, uuid, jsonb, text, boolean)
from public;
grant execute on function public.milhano_save_eod_submission(uuid, uuid, jsonb, text, boolean)
to service_role;

commit;

-- ------------------------------------------------------------
-- Validation
-- ------------------------------------------------------------
select
    to_regclass('public.milhano_eod_change_logs') is not null as log_table_exists,
    to_regclass('public.vw_milhano_eod_change_logs') is not null as log_view_exists;

select
    routine_name,
    security_type
from information_schema.routines
where routine_schema = 'public'
  and routine_name = 'milhano_save_eod_submission';
