export type PhoneCountry = {
  iso: string
  name: string
  dialCode: string
}

export const PHONE_COUNTRIES: PhoneCountry[] = [
  { iso: 'MX', name: 'México', dialCode: '+52' },
  { iso: 'CA', name: 'Canadá', dialCode: '+1' },
  { iso: 'US', name: 'Estados Unidos', dialCode: '+1' },
  { iso: 'AF', name: 'Afganistán', dialCode: '+93' },
  { iso: 'AL', name: 'Albania', dialCode: '+355' },
  { iso: 'DE', name: 'Alemania', dialCode: '+49' },
  { iso: 'AO', name: 'Angola', dialCode: '+244' },
  { iso: 'AI', name: 'Anguila', dialCode: '+1264' },
  { iso: 'AG', name: 'Antigua y Barbuda', dialCode: '+1268' },
  { iso: 'SA', name: 'Arabia Saudí', dialCode: '+966' },
  { iso: 'DZ', name: 'Argelia', dialCode: '+213' },
  { iso: 'AR', name: 'Argentina', dialCode: '+54' },
  { iso: 'AM', name: 'Armenia', dialCode: '+374' },
  { iso: 'AW', name: 'Aruba', dialCode: '+297' },
  { iso: 'AU', name: 'Australia', dialCode: '+61' },
  { iso: 'AT', name: 'Austria', dialCode: '+43' },
  { iso: 'AZ', name: 'Azerbaiyán', dialCode: '+994' },
  { iso: 'BS', name: 'Bahamas', dialCode: '+1242' },
  { iso: 'BD', name: 'Bangladés', dialCode: '+880' },
  { iso: 'BB', name: 'Barbados', dialCode: '+1246' },
  { iso: 'BH', name: 'Baréin', dialCode: '+973' },
  { iso: 'BZ', name: 'Belice', dialCode: '+501' },
  { iso: 'BJ', name: 'Benín', dialCode: '+229' },
  { iso: 'BM', name: 'Bermudas', dialCode: '+1441' },
  { iso: 'BY', name: 'Bielorrusia', dialCode: '+375' },
  { iso: 'BO', name: 'Bolivia', dialCode: '+591' },
  { iso: 'BA', name: 'Bosnia y Herzegovina', dialCode: '+387' },
  { iso: 'BW', name: 'Botsuana', dialCode: '+267' },
  { iso: 'BR', name: 'Brasil', dialCode: '+55' },
  { iso: 'BN', name: 'Brunéi', dialCode: '+673' },
  { iso: 'BG', name: 'Bulgaria', dialCode: '+359' },
  { iso: 'BF', name: 'Burkina Faso', dialCode: '+226' },
  { iso: 'BI', name: 'Burundi', dialCode: '+257' },
  { iso: 'BT', name: 'Bután', dialCode: '+975' },
  { iso: 'BE', name: 'Bélgica', dialCode: '+32' },
  { iso: 'CV', name: 'Cabo Verde', dialCode: '+238' },
  { iso: 'KH', name: 'Camboya', dialCode: '+855' },
  { iso: 'CM', name: 'Camerún', dialCode: '+237' },
  { iso: 'QA', name: 'Catar', dialCode: '+974' },
  { iso: 'TD', name: 'Chad', dialCode: '+235' },
  { iso: 'CZ', name: 'Chequia', dialCode: '+420' },
  { iso: 'CL', name: 'Chile', dialCode: '+56' },
  { iso: 'CN', name: 'China', dialCode: '+86' },
  { iso: 'CY', name: 'Chipre', dialCode: '+357' },
  { iso: 'CO', name: 'Colombia', dialCode: '+57' },
  { iso: 'KM', name: 'Comoras', dialCode: '+269' },
  { iso: 'CG', name: 'Congo', dialCode: '+242' },
  { iso: 'KP', name: 'Corea del Norte', dialCode: '+850' },
  { iso: 'KR', name: 'Corea del Sur', dialCode: '+82' },
  { iso: 'CR', name: 'Costa Rica', dialCode: '+506' },
  { iso: 'HR', name: 'Croacia', dialCode: '+385' },
  { iso: 'CU', name: 'Cuba', dialCode: '+53' },
  { iso: 'CI', name: 'Côte d’Ivoire', dialCode: '+225' },
  { iso: 'DK', name: 'Dinamarca', dialCode: '+45' },
  { iso: 'DM', name: 'Dominica', dialCode: '+1767' },
  { iso: 'EC', name: 'Ecuador', dialCode: '+593' },
  { iso: 'EG', name: 'Egipto', dialCode: '+20' },
  { iso: 'SV', name: 'El Salvador', dialCode: '+503' },
  { iso: 'AE', name: 'Emiratos Árabes Unidos', dialCode: '+971' },
  { iso: 'ER', name: 'Eritrea', dialCode: '+291' },
  { iso: 'SK', name: 'Eslovaquia', dialCode: '+421' },
  { iso: 'SI', name: 'Eslovenia', dialCode: '+386' },
  { iso: 'ES', name: 'España', dialCode: '+34' },
  { iso: 'EE', name: 'Estonia', dialCode: '+372' },
  { iso: 'SZ', name: 'Esuatini', dialCode: '+268' },
  { iso: 'ET', name: 'Etiopía', dialCode: '+251' },
  { iso: 'PH', name: 'Filipinas', dialCode: '+63' },
  { iso: 'FI', name: 'Finlandia', dialCode: '+358' },
  { iso: 'FJ', name: 'Fiyi', dialCode: '+679' },
  { iso: 'FR', name: 'Francia', dialCode: '+33' },
  { iso: 'GA', name: 'Gabón', dialCode: '+241' },
  { iso: 'GM', name: 'Gambia', dialCode: '+220' },
  { iso: 'GE', name: 'Georgia', dialCode: '+995' },
  { iso: 'GH', name: 'Ghana', dialCode: '+233' },
  { iso: 'GI', name: 'Gibraltar', dialCode: '+350' },
  { iso: 'GD', name: 'Granada', dialCode: '+1473' },
  { iso: 'GR', name: 'Grecia', dialCode: '+30' },
  { iso: 'GL', name: 'Groenlandia', dialCode: '+299' },
  { iso: 'GP', name: 'Guadalupe', dialCode: '+590' },
  { iso: 'GU', name: 'Guam', dialCode: '+1671' },
  { iso: 'GT', name: 'Guatemala', dialCode: '+502' },
  { iso: 'GF', name: 'Guayana Francesa', dialCode: '+594' },
  { iso: 'GG', name: 'Guernesey', dialCode: '+44' },
  { iso: 'GN', name: 'Guinea', dialCode: '+224' },
  { iso: 'GQ', name: 'Guinea Ecuatorial', dialCode: '+240' },
  { iso: 'GW', name: 'Guinea-Bisáu', dialCode: '+245' },
  { iso: 'GY', name: 'Guyana', dialCode: '+592' },
  { iso: 'HT', name: 'Haití', dialCode: '+509' },
  { iso: 'HN', name: 'Honduras', dialCode: '+504' },
  { iso: 'HU', name: 'Hungría', dialCode: '+36' },
  { iso: 'IN', name: 'India', dialCode: '+91' },
  { iso: 'ID', name: 'Indonesia', dialCode: '+62' },
  { iso: 'IQ', name: 'Irak', dialCode: '+964' },
  { iso: 'IE', name: 'Irlanda', dialCode: '+353' },
  { iso: 'IR', name: 'Irán', dialCode: '+98' },
  { iso: 'IM', name: 'Isla de Man', dialCode: '+44' },
  { iso: 'CX', name: 'Isla de Navidad', dialCode: '+61' },
  { iso: 'NF', name: 'Isla Norfolk', dialCode: '+672' },
  { iso: 'IS', name: 'Islandia', dialCode: '+354' },
  { iso: 'KY', name: 'Islas Caimán', dialCode: '+1345' },
  { iso: 'CC', name: 'Islas Cocos', dialCode: '+61' },
  { iso: 'CK', name: 'Islas Cook', dialCode: '+682' },
  { iso: 'FO', name: 'Islas Feroe', dialCode: '+298' },
  { iso: 'GS', name: 'Islas Georgia del Sur y Sandwich del Sur', dialCode: '+500' },
  { iso: 'FK', name: 'Islas Malvinas', dialCode: '+500' },
  { iso: 'MP', name: 'Islas Marianas del Norte', dialCode: '+1670' },
  { iso: 'MH', name: 'Islas Marshall', dialCode: '+692' },
  { iso: 'PN', name: 'Islas Pitcairn', dialCode: '+64' },
  { iso: 'SB', name: 'Islas Salomón', dialCode: '+677' },
  { iso: 'IL', name: 'Israel', dialCode: '+972' },
  { iso: 'IT', name: 'Italia', dialCode: '+39' },
  { iso: 'JM', name: 'Jamaica', dialCode: '+1876' },
  { iso: 'JP', name: 'Japón', dialCode: '+81' },
  { iso: 'JE', name: 'Jersey', dialCode: '+44' },
  { iso: 'JO', name: 'Jordania', dialCode: '+962' },
  { iso: 'KZ', name: 'Kazajistán', dialCode: '+76' },
  { iso: 'KE', name: 'Kenia', dialCode: '+254' },
  { iso: 'KG', name: 'Kirguistán', dialCode: '+996' },
  { iso: 'KI', name: 'Kiribati', dialCode: '+686' },
  { iso: 'KW', name: 'Kuwait', dialCode: '+965' },
  { iso: 'LA', name: 'Laos', dialCode: '+856' },
  { iso: 'LS', name: 'Lesoto', dialCode: '+266' },
  { iso: 'LV', name: 'Letonia', dialCode: '+371' },
  { iso: 'LR', name: 'Liberia', dialCode: '+231' },
  { iso: 'LY', name: 'Libia', dialCode: '+218' },
  { iso: 'LI', name: 'Liechtenstein', dialCode: '+423' },
  { iso: 'LT', name: 'Lituania', dialCode: '+370' },
  { iso: 'LU', name: 'Luxemburgo', dialCode: '+352' },
  { iso: 'LB', name: 'Líbano', dialCode: '+961' },
  { iso: 'MK', name: 'Macedonia del Norte', dialCode: '+389' },
  { iso: 'MG', name: 'Madagascar', dialCode: '+261' },
  { iso: 'MY', name: 'Malasia', dialCode: '+60' },
  { iso: 'MW', name: 'Malaui', dialCode: '+265' },
  { iso: 'MV', name: 'Maldivas', dialCode: '+960' },
  { iso: 'ML', name: 'Mali', dialCode: '+223' },
  { iso: 'MT', name: 'Malta', dialCode: '+356' },
  { iso: 'MA', name: 'Marruecos', dialCode: '+212' },
  { iso: 'MQ', name: 'Martinica', dialCode: '+596' },
  { iso: 'MU', name: 'Mauricio', dialCode: '+230' },
  { iso: 'MR', name: 'Mauritania', dialCode: '+222' },
  { iso: 'YT', name: 'Mayotte', dialCode: '+262' },
  { iso: 'FM', name: 'Micronesia', dialCode: '+691' },
  { iso: 'MD', name: 'Moldavia', dialCode: '+373' },
  { iso: 'MN', name: 'Mongolia', dialCode: '+976' },
  { iso: 'MS', name: 'Montserrat', dialCode: '+1664' },
  { iso: 'MZ', name: 'Mozambique', dialCode: '+258' },
  { iso: 'MC', name: 'Mónaco', dialCode: '+377' },
  { iso: 'NA', name: 'Namibia', dialCode: '+264' },
  { iso: 'NR', name: 'Nauru', dialCode: '+674' },
  { iso: 'NP', name: 'Nepal', dialCode: '+977' },
  { iso: 'NI', name: 'Nicaragua', dialCode: '+505' },
  { iso: 'NG', name: 'Nigeria', dialCode: '+234' },
  { iso: 'NU', name: 'Niue', dialCode: '+683' },
  { iso: 'NO', name: 'Noruega', dialCode: '+47' },
  { iso: 'NC', name: 'Nueva Caledonia', dialCode: '+687' },
  { iso: 'NZ', name: 'Nueva Zelanda', dialCode: '+64' },
  { iso: 'NE', name: 'Níger', dialCode: '+227' },
  { iso: 'OM', name: 'Omán', dialCode: '+968' },
  { iso: 'PK', name: 'Pakistán', dialCode: '+92' },
  { iso: 'PW', name: 'Palaos', dialCode: '+680' },
  { iso: 'PA', name: 'Panamá', dialCode: '+507' },
  { iso: 'PG', name: 'Papúa Nueva Guinea', dialCode: '+675' },
  { iso: 'PY', name: 'Paraguay', dialCode: '+595' },
  { iso: 'NL', name: 'Países Bajos', dialCode: '+31' },
  { iso: 'PE', name: 'Perú', dialCode: '+51' },
  { iso: 'PF', name: 'Polinesia Francesa', dialCode: '+689' },
  { iso: 'PL', name: 'Polonia', dialCode: '+48' },
  { iso: 'PT', name: 'Portugal', dialCode: '+351' },
  { iso: 'PR', name: 'Puerto Rico', dialCode: '+1787' },
  { iso: 'HK', name: 'RAE de Hong Kong (China)', dialCode: '+852' },
  { iso: 'MO', name: 'RAE de Macao (China)', dialCode: '+853' },
  { iso: 'GB', name: 'Reino Unido', dialCode: '+44' },
  { iso: 'CF', name: 'República Centroafricana', dialCode: '+236' },
  { iso: 'CD', name: 'República Democrática del Congo', dialCode: '+243' },
  { iso: 'DO', name: 'República Dominicana', dialCode: '+1809' },
  { iso: 'RE', name: 'Reunión', dialCode: '+262' },
  { iso: 'RW', name: 'Ruanda', dialCode: '+250' },
  { iso: 'RO', name: 'Rumanía', dialCode: '+40' },
  { iso: 'RU', name: 'Rusia', dialCode: '+7' },
  { iso: 'WS', name: 'Samoa', dialCode: '+685' },
  { iso: 'AS', name: 'Samoa Americana', dialCode: '+1684' },
  { iso: 'KN', name: 'San Cristóbal y Nieves', dialCode: '+1869' },
  { iso: 'SM', name: 'San Marino', dialCode: '+378' },
  { iso: 'PM', name: 'San Pedro y Miquelón', dialCode: '+508' },
  { iso: 'VC', name: 'San Vicente y las Granadinas', dialCode: '+1784' },
  { iso: 'SH', name: 'Santa Elena', dialCode: '+290' },
  { iso: 'LC', name: 'Santa Lucía', dialCode: '+1758' },
  { iso: 'ST', name: 'Santo Tomé y Príncipe', dialCode: '+239' },
  { iso: 'SN', name: 'Senegal', dialCode: '+221' },
  { iso: 'RS', name: 'Serbia', dialCode: '+381' },
  { iso: 'SC', name: 'Seychelles', dialCode: '+248' },
  { iso: 'SL', name: 'Sierra Leona', dialCode: '+232' },
  { iso: 'SG', name: 'Singapur', dialCode: '+65' },
  { iso: 'SY', name: 'Siria', dialCode: '+963' },
  { iso: 'SO', name: 'Somalia', dialCode: '+252' },
  { iso: 'LK', name: 'Sri Lanka', dialCode: '+94' },
  { iso: 'ZA', name: 'Sudáfrica', dialCode: '+27' },
  { iso: 'SD', name: 'Sudán', dialCode: '+249' },
  { iso: 'SS', name: 'Sudán del Sur', dialCode: '+211' },
  { iso: 'SE', name: 'Suecia', dialCode: '+46' },
  { iso: 'CH', name: 'Suiza', dialCode: '+41' },
  { iso: 'SR', name: 'Surinam', dialCode: '+597' },
  { iso: 'SJ', name: 'Svalbard y Jan Mayen', dialCode: '+4779' },
  { iso: 'EH', name: 'Sáhara Occidental', dialCode: '+212' },
  { iso: 'TH', name: 'Tailandia', dialCode: '+66' },
  { iso: 'TW', name: 'Taiwán', dialCode: '+886' },
  { iso: 'TZ', name: 'Tanzania', dialCode: '+255' },
  { iso: 'TJ', name: 'Tayikistán', dialCode: '+992' },
  { iso: 'IO', name: 'Territorio Británico del Océano Índico', dialCode: '+246' },
  { iso: 'TL', name: 'Timor-Leste', dialCode: '+670' },
  { iso: 'TG', name: 'Togo', dialCode: '+228' },
  { iso: 'TK', name: 'Tokelau', dialCode: '+690' },
  { iso: 'TO', name: 'Tonga', dialCode: '+676' },
  { iso: 'TT', name: 'Trinidad y Tobago', dialCode: '+1868' },
  { iso: 'TM', name: 'Turkmenistán', dialCode: '+993' },
  { iso: 'TR', name: 'Turquía', dialCode: '+90' },
  { iso: 'TV', name: 'Tuvalu', dialCode: '+688' },
  { iso: 'TN', name: 'Túnez', dialCode: '+216' },
  { iso: 'UA', name: 'Ucrania', dialCode: '+380' },
  { iso: 'UG', name: 'Uganda', dialCode: '+256' },
  { iso: 'UY', name: 'Uruguay', dialCode: '+598' },
  { iso: 'UZ', name: 'Uzbekistán', dialCode: '+998' },
  { iso: 'VU', name: 'Vanuatu', dialCode: '+678' },
  { iso: 'VE', name: 'Venezuela', dialCode: '+58' },
  { iso: 'VN', name: 'Vietnam', dialCode: '+84' },
  { iso: 'WF', name: 'Wallis y Futuna', dialCode: '+681' },
  { iso: 'YE', name: 'Yemen', dialCode: '+967' },
  { iso: 'DJ', name: 'Yibuti', dialCode: '+253' },
  { iso: 'ZM', name: 'Zambia', dialCode: '+260' },
  { iso: 'ZW', name: 'Zimbabue', dialCode: '+263' },
]

export const DEFAULT_PHONE_COUNTRY = 'MX'
